# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the default version of the site.
[es]
  languageCode = "es-es"

# Uncomment the lines below to configure your website in a second language.
[ca]
 languageCode = "ca"
 #contentDir = "content/ca"
 title = "Carlos Cámara Menoyo"
 [ca.params]
   #description = "Site description in Chinese..."
   role = "Arquitecte. Doctor. Professor. Estudiant."
 [[ca.menu.main]]
   name = "Inici"
   url = "#"
   weight = 1

[en]
  languageCode = "en-us"
  #contentDir = "content/en"
  title = "Carlos Cámara-Menoyo"
  [en.params]
    #description = "Site description in English"
    role = "Architect. PhD. Teacher. Learner.."
  [[en.menu.main]]
    name = "Home"
    url = "#"
    weight = 1
